PROGRAM _CYCLIC
<?xml version="1.0"?>
<?AutomationStudio Version=3.0.71?>
<!-- Automation Studio Generated XML Section -->
<networks maxcolumn="0">
	<network label="" comment="Any handshaking, etc added in the future can be checked here." row="1" column="0" commented="0">
		<row>
			<contact type="open" name="EStopClear"/>
			<line/>
			<line/>
			<coil type="open" name="AllSystemsOK"/>
		</row>
	</network>
</networks>
END_PROGRAM

